### ISSUE TITLE
Missing BusyFit.o file

### ISSUE THREAD

**Issue by amidou** [SoFiA-Admin/BusyFit#1]
I tried to compile BusyFit on two different systems (OSX and Linux) and each attempt results in a missing BusyFit.o file

**Comment by SoFiA-Admin** [comment]
Thank you for the notification. If the `BusyFit.o` file is missing, then the compilation of `BusyFit.cpp` must have failed. Without seeing the actual error message produced by the compiler, I can only speculate about the reason. My best guess would be that you might not have the GNU Scientific Library installed on your computer, as this is the only external dependency that BusyFit requires and therefore the only possible point where the compilation could fail.

Please ensure that the GSL is installed and then try to compile BusyFit again. If this doesn’t solve the problem, please post the error message from the compiler so that we can further investigate the cause of the compilation failure.

**Comment by amidou** [comment]
Oh my bad, I didn't notice that GSL was missing and that's what was causing the error. Thanks!
